'use client';
import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import Sidebar from '@/components/Sidebar';
import CaseNav from '@/components/CaseNav';
import { listDisputeRounds, autoGenerateDisputes, createDisputeRound, updateDisputeRound, createDisputeItem, updateDisputeItem, downloadDisputeLetter } from '@/lib/api';

interface DisputeItem { id: number; creditor_name: string; account_number_last4: string; dispute_reason: string; fcra_basis: string; status: string; resolution: string; }
interface Round { id: number; round_number: number; recipient_type: string; bureau: string; recipient_name: string; recipient_address: string; sent_date: string; response_due_date: string; response_received_date: string; certified_mail_tracking: string; status: string; notes: string; items: DisputeItem[]; }

const BUREAUS = ['experian', 'equifax', 'transunion', 'innovis'];
const RECIPIENT_TYPES = [
  { value: 'bureau', label: 'Credit Bureau' },
  { value: 'creditor', label: 'Original Creditor' },
  { value: 'collection_agency', label: 'Collection Agency' },
  { value: 'debt_buyer', label: 'Debt Buyer' },
];
const STATUSES = ['draft', 'preparing', 'sent', 'response_received', 'escalated', 'closed'];

export default function DisputesPage() {
  const { id } = useParams<{ id: string }>();
  const caseId = parseInt(id);
  const [rounds, setRounds] = useState<Round[]>([]);
  const [loading, setLoading] = useState(true);
  const [showRoundForm, setShowRoundForm] = useState(false);
  const [roundForm, setRoundForm] = useState({ recipient_type: 'bureau', bureau: 'experian', recipient_name: '', recipient_address: '', round_number: 1, sent_date: '', response_due_date: '', certified_mail_tracking: '', notes: '' });
  const [addItemRoundId, setAddItemRoundId] = useState<number | null>(null);
  const [itemForm, setItemForm] = useState({ creditor_name: '', account_number_last4: '', dispute_reason: '', fcra_basis: '' });
  const [autoGenerating, setAutoGenerating] = useState(false);
  const [autoError, setAutoError] = useState('');
  const [autoSuccess, setAutoSuccess] = useState('');
  const [trackingEdit, setTrackingEdit] = useState<Record<number, string>>({});

  function load() { listDisputeRounds(caseId).then(setRounds).finally(() => setLoading(false)); }
  useEffect(() => { load(); }, [caseId]);

  async function addRound(e: React.FormEvent) {
    e.preventDefault();
    await createDisputeRound({ ...roundForm, case_id: caseId, round_number: parseInt(String(roundForm.round_number)) });
    setShowRoundForm(false);
    load();
  }

  async function changeRoundStatus(roundId: number, status: string) {
    await updateDisputeRound(roundId, { status });
    load();
  }

  async function saveTracking(roundId: number) {
    await updateDisputeRound(roundId, { certified_mail_tracking: trackingEdit[roundId] || '' });
    load();
  }

  async function addItem(e: React.FormEvent) {
    e.preventDefault();
    if (!addItemRoundId) return;
    await createDisputeItem({ ...itemForm, round_id: addItemRoundId });
    setAddItemRoundId(null);
    setItemForm({ creditor_name: '', account_number_last4: '', dispute_reason: '', fcra_basis: '' });
    load();
  }

  async function changeItemStatus(itemId: number, status: string) {
    await updateDisputeItem(itemId, { status });
    load();
  }

  async function downloadLetter(roundId: number, round: Round) {
    try {
      const blob = await downloadDisputeLetter(roundId);
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      const recipientSlug = round.recipient_type === 'bureau' ? round.bureau : (round.recipient_name || round.recipient_type).replace(/\s+/g, '_').toLowerCase();
      a.download = `dispute_letter_${recipientSlug}_round${round.round_number}.txt`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err: unknown) {
      const e = err as { response?: { data?: { detail?: unknown } }; message?: string };
      const d = e.response?.data?.detail;
      setAutoError(typeof d === 'string' ? d : e.message || 'Download failed.');
    }
  }

  function getDueStatus(dueDateStr: string | null): { label: string; color: string } | null {
    if (!dueDateStr) return null;
    const due = new Date(dueDateStr);
    const now = new Date();
    const diffDays = Math.ceil((due.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
    if (diffDays < 0) return { label: `OVERDUE by ${Math.abs(diffDays)}d`, color: '#fee2e2' };
    if (diffDays <= 7) return { label: `Due in ${diffDays}d`, color: '#fef3c7' };
    return null;
  }

  async function autoGenerate() {
    setAutoGenerating(true); setAutoError(''); setAutoSuccess('');
    try {
      const r = await autoGenerateDisputes(caseId);
      setAutoSuccess(`Created ${r.rounds_created} round(s) and ${r.items_created} dispute item(s) from derogatory tradelines.`);
      load();
    } catch (err: unknown) {
      const e = err as { response?: { data?: { detail?: unknown } }; message?: string };
      const d = e.response?.data?.detail;
      setAutoError(typeof d === 'string' ? d : e.message || 'Auto-generate failed.');
    } finally { setAutoGenerating(false); }
  }

  function recipientLabel(round: Round) {
    if (round.recipient_type === 'bureau') return round.bureau?.toUpperCase() || 'BUREAU';
    return round.recipient_name || RECIPIENT_TYPES.find(r => r.value === round.recipient_type)?.label || round.recipient_type;
  }

  return (
    <div className="main-layout">
      <Sidebar />
      <main className="main-content">
        <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <div><h1>Dispute Tracker</h1><p>Bureau, creditor, and collector disputes with certified mail tracking</p></div>
          <div style={{ display: 'flex', gap: 8 }}>
            <button className="btn btn-outline" onClick={autoGenerate} disabled={autoGenerating}>{autoGenerating ? 'Generating…' : '⚡ Auto-generate'}</button>
            <button className="btn btn-primary" onClick={() => setShowRoundForm(s => !s)}>{showRoundForm ? 'Cancel' : '+ New Round'}</button>
          </div>
        </div>
        <CaseNav caseId={caseId} />
        {autoError && <div className="alert-error" style={{ marginBottom: 12 }}>{autoError}</div>}
        {autoSuccess && <div className="alert-success" style={{ marginBottom: 12 }}>{autoSuccess}</div>}

        {showRoundForm && (
          <div className="card" style={{ marginBottom: 16 }}>
            <h3>New Dispute Round</h3>
            <form onSubmit={addRound}>
              <div className="grid-2">
                <div className="form-group"><label>Recipient Type *</label>
                  <select value={roundForm.recipient_type} onChange={e => setRoundForm(f => ({ ...f, recipient_type: e.target.value }))}>
                    {RECIPIENT_TYPES.map(r => <option key={r.value} value={r.value}>{r.label}</option>)}
                  </select>
                </div>
                <div className="form-group"><label>Round #</label>
                  <input type="number" min={1} value={roundForm.round_number} onChange={e => setRoundForm(f => ({ ...f, round_number: parseInt(e.target.value) }))} />
                </div>
                {roundForm.recipient_type === 'bureau' ? (
                  <div className="form-group"><label>Bureau *</label>
                    <select value={roundForm.bureau} onChange={e => setRoundForm(f => ({ ...f, bureau: e.target.value }))}>
                      {BUREAUS.map(b => <option key={b} value={b}>{b}</option>)}
                    </select>
                  </div>
                ) : (
                  <>
                    <div className="form-group"><label>Recipient Name *</label>
                      <input required value={roundForm.recipient_name} onChange={e => setRoundForm(f => ({ ...f, recipient_name: e.target.value }))} placeholder="e.g., LVNV Funding LLC" />
                    </div>
                    <div className="form-group" style={{ gridColumn: '1/-1' }}><label>Recipient Address</label>
                      <textarea rows={2} value={roundForm.recipient_address} onChange={e => setRoundForm(f => ({ ...f, recipient_address: e.target.value }))} placeholder="Street, City, State ZIP" />
                    </div>
                  </>
                )}
                <div className="form-group"><label>Sent Date</label><input type="date" value={roundForm.sent_date} onChange={e => setRoundForm(f => ({ ...f, sent_date: e.target.value }))} /></div>
                <div className="form-group"><label>Response Due</label><input type="date" value={roundForm.response_due_date} onChange={e => setRoundForm(f => ({ ...f, response_due_date: e.target.value }))} /></div>
                <div className="form-group"><label>Certified Mail Tracking #</label><input value={roundForm.certified_mail_tracking} onChange={e => setRoundForm(f => ({ ...f, certified_mail_tracking: e.target.value }))} placeholder="USPS tracking number" /></div>
                <div className="form-group" style={{ gridColumn: '1/-1' }}><label>Notes</label><textarea rows={2} value={roundForm.notes} onChange={e => setRoundForm(f => ({ ...f, notes: e.target.value }))} /></div>
              </div>
              <button type="submit" className="btn btn-primary btn-sm">Create Round</button>
            </form>
          </div>
        )}

        {loading ? <div className="spinner" /> : rounds.length === 0 ? (
          <div className="card"><p className="empty">No dispute rounds yet. Click &quot;Auto-generate&quot; or &quot;+ New Round&quot; to start.</p></div>
        ) : (
          rounds.map(round => (
            <div key={round.id} className="card" style={{ marginBottom: 16 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8, flexWrap: 'wrap', gap: 8 }}>
                <div>
                  <h3 style={{ marginBottom: 2 }}>Round {round.round_number} — {recipientLabel(round)}</h3>
                  <span style={{ fontSize: 11, color: 'var(--muted)', background: 'var(--bg)', padding: '2px 6px', borderRadius: 4 }}>
                    {RECIPIENT_TYPES.find(r => r.value === round.recipient_type)?.label || round.recipient_type}
                  </span>
                </div>
                <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>
                  <select value={round.status} onChange={e => changeRoundStatus(round.id, e.target.value)}
                    style={{ fontSize: 12, padding: '4px 8px', borderRadius: 4, border: '1px solid var(--border)' }}>
                    {STATUSES.map(s => <option key={s} value={s}>{s.replace('_', ' ')}</option>)}
                  </select>
                  <button className="btn btn-primary btn-sm" onClick={() => downloadLetter(round.id, round)}>⬇ Download Letter</button>
                  <button className="btn btn-outline btn-sm" onClick={() => setAddItemRoundId(addItemRoundId === round.id ? null : round.id)}>+ Item</button>
                </div>
              </div>

              <div style={{ display: 'flex', gap: 24, fontSize: 12, color: 'var(--muted)', marginBottom: 8, flexWrap: 'wrap', alignItems: 'center' }}>
                {round.sent_date && <span>Sent: {round.sent_date}</span>}
                {round.response_due_date && (
                  <span>Due: {round.response_due_date}
                    {(() => { const ds = getDueStatus(round.response_due_date); return ds ? <span style={{ background: ds.color, color: '#7c2d12', borderRadius: 4, padding: '2px 6px', fontSize: 11, fontWeight: 700, marginLeft: 6 }}>⏰ {ds.label}</span> : null; })()}
                  </span>
                )}
                {round.response_received_date && <span style={{ color: 'var(--success)' }}>Received: {round.response_received_date}</span>}
              </div>

              {/* Certified mail tracking */}
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12, fontSize: 12 }}>
                <span style={{ color: 'var(--muted)', whiteSpace: 'nowrap' }}>📮 Tracking #:</span>
                <input
                  value={trackingEdit[round.id] !== undefined ? trackingEdit[round.id] : (round.certified_mail_tracking || '')}
                  onChange={e => setTrackingEdit(t => ({ ...t, [round.id]: e.target.value }))}
                  placeholder="Enter USPS certified mail tracking number"
                  style={{ flex: 1, padding: '4px 8px', border: '1px solid var(--border)', borderRadius: 4, fontSize: 12 }}
                />
                {trackingEdit[round.id] !== undefined && (
                  <button className="btn btn-primary btn-sm" onClick={() => saveTracking(round.id)}>Save</button>
                )}
              </div>

              {addItemRoundId === round.id && (
                <form onSubmit={addItem} style={{ marginBottom: 12, padding: 12, background: 'var(--bg)', borderRadius: 'var(--radius)' }}>
                  <div className="grid-2">
                    <div className="form-group"><label>Creditor *</label><input required value={itemForm.creditor_name} onChange={e => setItemForm(f => ({ ...f, creditor_name: e.target.value }))} /></div>
                    <div className="form-group"><label>Account Last 4</label><input maxLength={4} value={itemForm.account_number_last4} onChange={e => setItemForm(f => ({ ...f, account_number_last4: e.target.value.replace(/\D/g, '').slice(0, 4) }))} /></div>
                    <div className="form-group"><label>Dispute Reason *</label><input required value={itemForm.dispute_reason} onChange={e => setItemForm(f => ({ ...f, dispute_reason: e.target.value }))} placeholder="e.g., Not my account, Incorrect balance" /></div>
                    <div className="form-group"><label>Legal Basis</label><input value={itemForm.fcra_basis} onChange={e => setItemForm(f => ({ ...f, fcra_basis: e.target.value }))} placeholder="e.g., FCRA §611, FDCPA §809" /></div>
                  </div>
                  <button type="submit" className="btn btn-primary btn-sm">Add Item</button>
                </form>
              )}

              {round.items?.length > 0 && (
                <table>
                  <thead><tr><th>Creditor</th><th>Account</th><th>Reason</th><th>Legal Basis</th><th>Status</th><th>Resolution</th></tr></thead>
                  <tbody>
                    {round.items.map(item => (
                      <tr key={item.id}>
                        <td>{item.creditor_name}</td>
                        <td><code>xxxx-{item.account_number_last4}</code></td>
                        <td style={{ fontSize: 12 }}>{item.dispute_reason}</td>
                        <td><code style={{ fontSize: 11 }}>{item.fcra_basis || '—'}</code></td>
                        <td>
                          <select value={item.status} onChange={e => changeItemStatus(item.id, e.target.value)}
                            style={{ fontSize: 11, padding: '2px 6px', borderRadius: 3, border: '1px solid var(--border)' }}>
                            <option value="pending">Pending</option>
                            <option value="deleted">Deleted</option>
                            <option value="updated">Updated</option>
                            <option value="verified">Verified</option>
                            <option value="no_response">No Response</option>
                          </select>
                        </td>
                        <td style={{ fontSize: 12, color: 'var(--muted)' }}>{item.resolution || '—'}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>
          ))
        )}
      </main>
    </div>
  );
}
