"""create_repo_review_tables

Revision ID: 7090752f05b4
Revises: 4c81bcdc7195
Create Date: 2026-06-22 17:37:15.820527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7090752f05b4'
down_revision: Union[str, None] = '4c81bcdc7195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_url', sa.String(length=1000), nullable=False),
    sa.Column('repo_name', sa.String(length=500), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='reviewstatus', native_enum=False), nullable=False),
    sa.Column('classification', sa.Enum('USE_DIRECTLY', 'MODIFY_FIRST', 'REFERENCE_ONLY', 'DO_NOT_USE', name='repoclassification', native_enum=False), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('triggered_by_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_reviews_repo_name'), 'repo_reviews', ['repo_name'], unique=False)
    op.create_index(op.f('ix_repo_reviews_status'), 'repo_reviews', ['status'], unique=False)
    op.create_table('review_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('classification', sa.Enum('USE_DIRECTLY', 'MODIFY_FIRST', 'REFERENCE_ONLY', 'DO_NOT_USE', name='repoclassification', native_enum=False), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('stage_scores', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('blockers', sa.JSON(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('generated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['repo_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_reports_review_id'), 'review_reports', ['review_id'], unique=True)
    op.create_table('review_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('stage_type', sa.Enum('LICENSE', 'SECURITY', 'DEPENDENCY', 'CAPABILITY', 'INTEGRATION', name='stagetype', native_enum=False), nullable=False),
    sa.Column('verdict', sa.Enum('PASS', 'WARN', 'FAIL', 'SKIP', name='stageverdict', native_enum=False), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['repo_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_stages_review_id'), 'review_stages', ['review_id'], unique=False)
    op.create_table('review_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['review_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_findings_severity'), 'review_findings', ['severity'], unique=False)
    op.create_index(op.f('ix_review_findings_stage_id'), 'review_findings', ['stage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_findings_stage_id'), table_name='review_findings')
    op.drop_index(op.f('ix_review_findings_severity'), table_name='review_findings')
    op.drop_table('review_findings')
    op.drop_index(op.f('ix_review_stages_review_id'), table_name='review_stages')
    op.drop_table('review_stages')
    op.drop_index(op.f('ix_review_reports_review_id'), table_name='review_reports')
    op.drop_table('review_reports')
    op.drop_index(op.f('ix_repo_reviews_status'), table_name='repo_reviews')
    op.drop_index(op.f('ix_repo_reviews_repo_name'), table_name='repo_reviews')
    op.drop_table('repo_reviews')
    # ### end Alembic commands ###
