"""create_memory_context_knowledge_tables

Revision ID: b4cc0ab7bb6a
Revises: 805db7d97b2b
Create Date: 2026-06-22 17:30:57.039220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b4cc0ab7bb6a'
down_revision: Union[str, None] = '805db7d97b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_tags_name'), 'memory_tags', ['name'], unique=True)
    op.create_table('decision_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'ACCEPTED', 'DEPRECATED', 'SUPERSEDED', name='decisionstatus', native_enum=False), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('consequences', sa.Text(), nullable=True),
    sa.Column('alternatives', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_records_status'), 'decision_records', ['status'], unique=False)
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('node_type', sa.Enum('CONCEPT', 'ENTITY', 'FACT', 'PROCEDURE', 'PRINCIPLE', 'RELATIONSHIP', name='nodetype', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_nodes_node_type'), 'knowledge_nodes', ['node_type'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_title'), 'knowledge_nodes', ['title'], unique=False)
    op.create_table('knowledge_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('edge_count', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_collections_name'), 'memory_collections', ['name'], unique=True)
    op.create_table('project_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('state_type', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_states_project_name'), 'project_states', ['project_name'], unique=False)
    op.create_table('context_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('BUILDING', 'READY', 'STALE', 'FAILED', name='contextstatus', native_enum=False), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_packages_agent_id'), 'context_packages', ['agent_id'], unique=False)
    op.create_index(op.f('ix_context_packages_name'), 'context_packages', ['name'], unique=False)
    op.create_table('knowledge_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=False),
    sa.Column('edge_type', sa.Enum('IS_A', 'HAS_A', 'RELATED_TO', 'IMPLIES', 'REQUIRES', 'CONTRADICTS', 'CAUSES', 'USED_BY', name='edgetype', native_enum=False), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_edges_source_node_id'), 'knowledge_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_target_node_id'), 'knowledge_edges', ['target_node_id'], unique=False)
    op.create_table('memory_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Enum('TEXT', 'CODE', 'URL', 'FILE', 'JSON', name='contenttype', native_enum=False), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['memory_collections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_entries_collection_id'), 'memory_entries', ['collection_id'], unique=False)
    op.create_table('context_rebuild_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('triggered_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='rebuildstatus', native_enum=False), nullable=False),
    sa.Column('sources_scanned', sa.Integer(), nullable=False),
    sa.Column('sources_included', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['context_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_rebuild_runs_package_id'), 'context_rebuild_runs', ['package_id'], unique=False)
    op.create_table('context_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('MEMORY', 'FILE', 'URL', 'KNOWLEDGE', 'TOOL_OUTPUT', name='contextsourcetype', native_enum=False), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_included', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['context_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_sources_package_id'), 'context_sources', ['package_id'], unique=False)
    op.create_table('memory_entry_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['memory_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['memory_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'tag_id', name='uq_memory_entry_tag')
    )
    op.create_index(op.f('ix_memory_entry_tags_entry_id'), 'memory_entry_tags', ['entry_id'], unique=False)
    op.create_index(op.f('ix_memory_entry_tags_tag_id'), 'memory_entry_tags', ['tag_id'], unique=False)
    op.create_table('memory_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_entry_id', sa.Integer(), nullable=False),
    sa.Column('target_entry_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.Enum('RELATED', 'CONTRADICTS', 'SUPPORTS', 'DERIVED_FROM', 'SUPERSEDES', name='memorylinktype', native_enum=False), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_entry_id'], ['memory_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entry_id'], ['memory_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_links_source_entry_id'), 'memory_links', ['source_entry_id'], unique=False)
    op.create_index(op.f('ix_memory_links_target_entry_id'), 'memory_links', ['target_entry_id'], unique=False)
    op.create_table('memory_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Enum('TEXT', 'CODE', 'URL', 'FILE', 'JSON', name='contenttype', native_enum=False), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entry_id'], ['memory_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_versions_entry_id'), 'memory_versions', ['entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_versions_entry_id'), table_name='memory_versions')
    op.drop_table('memory_versions')
    op.drop_index(op.f('ix_memory_links_target_entry_id'), table_name='memory_links')
    op.drop_index(op.f('ix_memory_links_source_entry_id'), table_name='memory_links')
    op.drop_table('memory_links')
    op.drop_index(op.f('ix_memory_entry_tags_tag_id'), table_name='memory_entry_tags')
    op.drop_index(op.f('ix_memory_entry_tags_entry_id'), table_name='memory_entry_tags')
    op.drop_table('memory_entry_tags')
    op.drop_index(op.f('ix_context_sources_package_id'), table_name='context_sources')
    op.drop_table('context_sources')
    op.drop_index(op.f('ix_context_rebuild_runs_package_id'), table_name='context_rebuild_runs')
    op.drop_table('context_rebuild_runs')
    op.drop_index(op.f('ix_memory_entries_collection_id'), table_name='memory_entries')
    op.drop_table('memory_entries')
    op.drop_index(op.f('ix_knowledge_edges_target_node_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_source_node_id'), table_name='knowledge_edges')
    op.drop_table('knowledge_edges')
    op.drop_index(op.f('ix_context_packages_name'), table_name='context_packages')
    op.drop_index(op.f('ix_context_packages_agent_id'), table_name='context_packages')
    op.drop_table('context_packages')
    op.drop_index(op.f('ix_project_states_project_name'), table_name='project_states')
    op.drop_table('project_states')
    op.drop_index(op.f('ix_memory_collections_name'), table_name='memory_collections')
    op.drop_table('memory_collections')
    op.drop_table('knowledge_snapshots')
    op.drop_index(op.f('ix_knowledge_nodes_title'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_node_type'), table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    op.drop_index(op.f('ix_decision_records_status'), table_name='decision_records')
    op.drop_table('decision_records')
    op.drop_index(op.f('ix_memory_tags_name'), table_name='memory_tags')
    op.drop_table('memory_tags')
    # ### end Alembic commands ###
