"""add_metro2_fields_users_audit

Revision ID: 5efe1b9e82b5
Revises: 
Create Date: 2026-06-16 22:45:38.397937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5efe1b9e82b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('metro2_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('tradeline_id', sa.Integer(), nullable=True),
    sa.Column('rule_code', sa.String(), nullable=True),
    sa.Column('rule_name', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fcra_section', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['aegis_cases.id'], ),
    sa.ForeignKeyConstraint(['tradeline_id'], ['tradelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metro2_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metro2_findings_id'), ['id'], unique=False)

    with op.batch_alter_table('tradelines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('high_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('past_due_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_payment_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_rating', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('compliance_condition_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('consumer_information_indicator', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dofd', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date_reported', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('raw_source_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tradelines', schema=None) as batch_op:
        batch_op.drop_column('raw_source_text')
        batch_op.drop_column('remarks')
        batch_op.drop_column('date_reported')
        batch_op.drop_column('dofd')
        batch_op.drop_column('consumer_information_indicator')
        batch_op.drop_column('compliance_condition_code')
        batch_op.drop_column('payment_rating')
        batch_op.drop_column('scheduled_payment_amount')
        batch_op.drop_column('past_due_amount')
        batch_op.drop_column('high_balance')

    with op.batch_alter_table('metro2_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metro2_findings_id'))

    op.drop_table('metro2_findings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
